### ISSUE TITLE
Logo with the "Laravel" word on it?

### ISSUE THREAD

**Issue by javiereguiluz** [laravel/art#6]
Hi all,

We've just unveil the [redesign of the symfony.com website](http://symfony.com/blog/introducing-the-new-symfony-com) and on the new homepage we now highlight some important PHP projects using Symfony components. Laravel of course is one of those projects.

Our problem is that we cannot find the Laravel logo with the "Laravel" word on it. Our designer had to recreate it, but since we want all logos to look stunning, I wonder if it could be possible to add some more artwork for the Laravel logo.

**Comment by javiereguiluz** [comment]
Closing this ancient issue as "won't fix".

**Comment by taylorotwell** [comment]
If someone can contribute it I will accept it. I have no ability to do it myself.
